language: cpp

os: linux

dist: trusty

compiler:
  - clang

env:
  global:
  - CMAKE_DIR=$HOME/cmake
  - CMAKE_GENERATOR=Ninja
  - TESTS_TARGET=test

before_install: 
  - sudo apt-get update
  - sudo apt-get -y install libhdf5-dev
  - sudo apt-get -y install libeigen3-dev
  - mkdir $CMAKE_DIR
  - wget http://www.cmake.org/files/v3.19/cmake-3.19.0-rc1-Linux-x86_64.tar.gz
  - tar --strip-components=1 -xz -C $CMAKE_DIR cmake-3.19.0-rc1-Linux-x86_64.tar.gz
  - export PATH=$CMAKE_DIR/bin/:$PATH

before_script:
  - clang --version
  - cmake --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - clang --version
  - cmake --version
  - mkdir -p build && pushd build
  - >
    cmake --warn-uninitialized --debug-output
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
    -DH5GT_PARALLEL_HDF5:BOOL=OFF
    -DH5GT_USE_EIGEN:BOOL=ON
    -DH5GT_USE_XTENSOR:BOOL=OFF
    -DH5GT_USE_OPENCV:BOOL=OFF
    -DEigen3_ROOT:PATH=$HOME/eigen
    -G "${CMAKE_GENERATOR}" ../
  - $CMAKE_DIR/bin/cmake --build .
  - CTEST_OUTPUT_ON_FAILURE=1 $CMAKE_DIR/bin/cmake --build . --target ${TESTS_TARGET}
  - popd
  - bash tests/test_project_integration.sh;