name: CICDAction

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  Eigen3_ROOT: $HOME/eigen

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: echo $HOME
      run: echo $HOME

    - name: Install Ninja
      run: sudo apt-get -y install ninja-build
    
    - name: Install HDF5
      run: sudo apt-get -y install libhdf5-dev
    
    - name: Install Eigen3
      run: git clone --branch 3.4 https://gitlab.com/libeigen/eigen.git $Eigen3_ROOT
      
    - name: CMake version
      run: cmake --version
      
    - name: Make dir "build" and cd
      run: mkdir -p build && cd build
      
    - name: Run CMake
      run: echo $PWD && cmake --warn-uninitialized --debug-output \
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
        -DH5GT_PARALLEL_HDF5:BOOL=OFF \
        -DH5GT_USE_EIGEN:BOOL=ON \ 
        -DH5GT_USE_XTENSOR:BOOL=OFF \
        -DH5GT_USE_OPENCV:BOOL=OFF \
        -DEigen3_ROOT:PATH=$Eigen3_ROOT \
        -G "Ninja" ../
